# Generated by Django 3.2.15 on 2022-08-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(default='ref'),
            preserve_default=False,
        ),
    ]
